name       : python-twisted
version    : 17.9.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/T/Twisted/Twisted-17.9.0.tar.bz2 : 0da1a7e35d5fcae37bc9c7978970b5feb3bc82822155b8654ec63925c05af75c
license    : MIT
component  : programming.python
summary    : Python Twisted module
description: |
    Twisted is an event-driven networking engine written in Python and licensed under the open source ​MIT license. Twisted runs on Python 2 and an ever growing subset also works with Python 3.
builddeps  :
    - pkgconfig(python3)
    - python-incremental
    - python-setuptools
rundeps    :
    - python-automat
    - python-constantly
    - python-hyperlink
    - python-incremental
    - python-openssl
    - python-service-identity
    - python-zope.interface
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
