name       : python-twisted
version    : 15.5.0
release    : 1
source     :
    - https://pypi.python.org/packages/source/T/Twisted/Twisted-15.5.0.tar.bz2 : a8046804a0dfae090234bbb90fc560a6cc11a208b3d048b55244c79c1945c17f
license    : MIT
summary    : Python Twisted module
description: |
    Twisted is an event-driven networking engine written in Python and licensed under the open source ​MIT license. Twisted runs on Python 2 and an ever growing subset also works with Python 3.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
