name       : python-twisted
version    : 21.7.0
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/T/Twisted/Twisted-21.7.0.tar.gz : 2cd652542463277378b0d349f47c62f20d9306e57d1247baabd6d1d38a109006
homepage   : https://www.twistedmatrix.com
license    : MIT
component  : programming.python
summary    : Python Twisted module
description: |
    Twisted is an event-driven networking engine written in Python and licensed under the open source MIT license.
builddeps  :
    - pkgconfig(python3)
    - python-incremental
rundeps    :
    - python-automat
    - python-constantly
    - python-hyperlink
    - python-incremental
    - python-pyhamcrest
    - python-service-identity
    - python-zope.interface
build      : |
    %python3_setup
install    : |
    %python3_install
