name       : python-twisted
version    : 22.4.0
release    : 13
source     :
    - https://files.pythonhosted.org/packages/source/T/Twisted/Twisted-22.4.0.tar.gz : a047990f57dfae1e0bd2b7df2526d4f16dcdc843774dc108b78c52f2a5f13680
homepage   : https://www.twistedmatrix.com
license    : MIT
component  : programming.python
summary    : Python Twisted module
description: |
    Twisted is an event-driven networking engine written in Python and licensed under the open source MIT license.
builddeps  :
    - pkgconfig(python3)
    - python-incremental
rundeps    :
    - python-automat
    - python-constantly
    - python-hyperlink
    - python-incremental
    - python-pyhamcrest
    - python-service-identity
    - python-typing-extensions
    - python-zope.interface
build      : |
    %python3_setup
install    : |
    %python3_install
