name       : python-twisted
version    : 20.3.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/T/Twisted/Twisted-20.3.0.tar.bz2 : d72c55b5d56e176563b91d11952d13b01af8725c623e498db5507b6614fc1e10
homepage   : https://www.twistedmatrix.com
license    : MIT
component  : programming.python
summary    : Python Twisted module
description: |
    Twisted is an event-driven networking engine written in Python and licensed under the open source MIT license.
builddeps  :
    - pkgconfig(python3)
    - python-incremental
rundeps    :
    - python-automat
    - python-constantly
    - python-hyperlink
    - python-incremental
    - python-pyhamcrest
    - python-service-identity
    - python-zope.interface
build      : |
    %python3_setup
install    : |
    %python3_install
