name       : python-twisted
version    : 19.7.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/61/31/3855dcacd1d3b2e60c0b4ccc8e727b8cd497bd7087d327d81a9f0cbb580c/Twisted-19.7.0.tar.bz2 : d5db93026568f60cacdc0615fcd21d46f694a6bfad0ef3ff53cde2b4bb85a39d
license    : MIT
component  : programming.python
summary    : Python Twisted module
description: |
    Twisted is an event-driven networking engine written in Python and licensed under the open source ​MIT license. Twisted runs on Python 2 and an ever growing subset also works with Python 3.
builddeps  :
    - pkgconfig(python3)
    - python-incremental
    - python-setuptools
rundeps    :
    - python-automat
    - python-attrs
    - python-constantly
    - python-hyperlink
    - python-incremental
    - python-pyhamcrest
    - python-openssl
    - python-service-identity
    - python-zope.interface
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
